---
# Copyright (c) Microsoft Corporation. All Rights Reserved.
# Licensed under the MIT license. See LICENSE file on the project webpage for details.

# Sample Open edX on Azure configuration
# see: https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml

# Database configuration for scalable ARM template
ORA_MYSQL_HOST: "openedx-mysql"
XQUEUE_MYSQL_HOST: "openedx-mysql"
EDXAPP_MYSQL_HOST: "openedx-mysql"
EDXAPP_MEMCACHE: ["openedx-mysql:11211"]
MONGO_BIND_IP: "0.0.0.0"
FORUM_MONGO_HOSTS: ["openedx-mongo"]
EDXAPP_MONGO_HOSTS: ["openedx-mongo"]
