---

- name: Run OXA script
  sudo: yes
  shell: mysql edxapp -h "{{ EDXAPP_MYSQL_HOST }}" -u "{{ EDXAPP_MYSQL_USER_ADMIN }}" -p"{{ EDXAPP_MYSQL_PASSWORD_ADMIN }}" < edxapp.sql
  args:
    chdir: "{{ mysql_files_path }}"
  register: bash

# Print the shell task's stdout and stderr.
- debug: var="bash.stdout_lines + [ bash.stderr ]"
